language: android
sudo: true
android:
  components:
   - build-tools-23.0.1
   - android-23
   - extra-android-m2repository
   - extra-google-m2repository
  licenses:
   - android-sdk-license-.+

branches:
  only:
   - master

before_install:
 - chmod +x gradlew

script: ./gradlew :library:check